import{a as L,S,i}from"./assets/vendor-BjmtRwYh.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const b="45288911-2aee760e8debc477a1c950329",q="https://pixabay.com/api/";async function d(r,o=1,a=15){const s=new URLSearchParams({key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:a});try{return(await L.get(`${q}?${s.toString()}`)).data}catch(e){throw console.error("Error fetching images:",e),e}}const u=document.querySelector(".gallery");function m(r){const o=r.map(({webformatURL:a,largeImageURL:s,tags:e,likes:t,views:n,comments:y,downloads:g})=>`
    <li>
      <a href="${s}">
        <img src="${a}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p>Likes:<br /><span>${t}</span></p>
        <p>Views:<br /><span>${n}</span></p>
        <p>Comments:<br /><span>${y}</span></p>
        <p>Downloads:<br /><span>${g}</span></p>
      </div>
    </li>
  `).join("");u.insertAdjacentHTML("beforeend",o),new S(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function w(){u.innerHTML=""}function p(){document.querySelector(".loader").classList.remove("hidden")}function f(){document.querySelector(".loader").classList.add("hidden")}function v(){document.querySelector("#load-more").classList.remove("hidden")}function h(){document.querySelector("#load-more").classList.add("hidden")}const E=document.querySelector(".search-form"),$=document.querySelector("#load-more");let l="",c=1;E.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.currentTarget.elements.query.value.trim(),c=1,!l){i.error({message:"Please enter a search query!",position:"topRight"});return}w(),h(),p();try{const o=await d(l,c);o.hits.length===0?i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(m(o.hits),v())}catch(o){i.error({title:"Error",message:o.message})}finally{f()}});$.addEventListener("click",async()=>{c+=1,p();try{const r=await d(l,c);m(r.hits),c*15>=r.totalHits?(h(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):P()}catch(r){i.error({title:"Error",message:r.message})}finally{f()}});function P(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
